name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
  custom_rules_path:
    description: "Path to a file with custom review rules."
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      run: npm install
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Run Reviewer
      run: node ${{ github.action_path }}/lib/main.js
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        INPUT_OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        INPUT_OPENAI_API_MODEL: ${{ inputs.OPENAI_API_MODEL }}
        INPUT_EXCLUDE: ${{ inputs.exclude }}
        INPUT_CUSTOM_RULES_PATH: ${{ inputs.custom_rules_path }}
branding:
  icon: "aperture"
  color: "green"
